In [1]:
from acidwatch import Client
import pandas as pd

session = Client()

In [2]:
session.list_models()

Models(root=[Model(access_error=None, model_id='tocomo', display_name='ToCoMo', description='The Total Consumption Model (ToCoMo) estimates final concentrations of chemicals based on initial input concentrations using a series of chemical reactions. \n\nThe model applies the following reactions in a specific order:\n\n3. H₂S + 3 NO₂ → SO₂ + H₂O + 3 NO\n2. 2 NO + O₂ → 2 NO₂\n1. NO₂ + SO₂ + H₂O → NO + H₂SO₄\n4. 3 NO₂ + H₂O → 2 HNO₃ + NO\n5. 2 NO₂ + H₂O → HNO₃ + HNO₂\n6. 8 H₂S + 4 O₂ → 8 H₂O + S₈\n\nThe model operates as follows:\nWe go through the list in the order given and try to apply the reaction. \nIf it is not possible with the current reaction, we proceed to the next one.\nIf a reaction can occur, it will be applied, and then we start from the top again.\n\nThis iterative approach allows ToCoMo to simulate the chemical interactions and provide estimates of final concentrations based on the initial conditions.\n', valid_substances=['O2', 'H2O', 'H2S', 'SO2', 'NO2'], parameters={}), Model(access_error=None, model_id='arcs', display_name='ARCS', description='Automated Reactions for CO2 Storage (ARCS) model.\n    ARCS combines first-principles calculations with Monte-Carlo sampling and models possible reactions that may occur under a given set of conditions.\n    This process identifies the most frequently occurring reactions and paths, final products, and expected concentrations.\n    \n    Source code found at https://github.com/equinor/arcs/tree/21ded96960d28d549c0950fbc1aa09c94159f652\n    ', valid_substances=['CH2O2', 'CH3CH2OH', 'CO', 'H2', 'O2', 'CH3COOH', 'CH3OH', 'CH4', 'CH3CHO', 'H2CO', 'H2O', 'H2SO4', 'H2S', 'S8', 'SO2', 'H2SO3', 'HNO3', 'NO2', 'NH3', 'HNO2', 'NO', 'N2', 'NOHSO4'], parameters={}), Model(access_error=None, model_id='arcs_exp', display_name='ARCS experimental', description='Automated Reactions for CO2 Storage (ARCS) model.\n    ARCS combines first-principles calculations with Monte-Carlo sampling and models possible reactions that may occur under a given set of conditions.\n    This process identifies the most frequently occurring reactions and paths, final products, and expected concentrations.\n    \n    This model is under significant development and expected to deviate while developed. Therefore a development version of it has been released while work is ongoing\n    Source code found at https://github.com/badw/arcs\n    ', valid_substances=['CH2O2', 'CH3CH2OH', 'CO', 'H2', 'O2', 'CH3COOH', 'CH3OH', 'CH4', 'CH3CHO', 'H2CO', 'H2O', 'H2SO4', 'H2S', 'S8', 'SO2', 'H2SO3', 'HNO3', 'NO2', 'NH3', 'HNO2', 'NO', 'N2', 'NOHSO4'], parameters={}), Model(access_error=None, model_id='solubilityccs', display_name='Solubility CCS', description='Solubility model detects acid formation risks in CO2 streams. \n    \nIt uses the SRK-CPA (Soave-Redlich-Kwong Cubic Plus Association) equation of state to calculate fugacity coefficients and activity models to determine component activities in multiphase systems.\n\nThe model currently supports the following chemical systems:\nCO₂-water (binary system)\nCO₂-water-H₂SO₄ (ternary system with sulfuric acid)\nCO₂-water-HNO₃ (ternary system with nitric acid)', valid_substances=['H2O', 'H2SO4', 'HNO3'], parameters={'flowRate': _Parameter(default=10, label='Flow rate', unit='Mt/year', type='number')}), Model(access_error=None, model_id='gibbs_minimization', display_name='Gibbs Minimization Model', description="The model's primary advantage lies in its ability to analyze complex systems, such as CO2 with impurities, without the need to specify individual reactions. By focusing only on the thermodynamic principles that govern the system's behavior, it identifies the stable state corresponding to the minimum total Gibbs free energy at given temperature and pressure.\n\nHowever, the model also has limitations. It requires the input of all possible species that could form from the elements present missing any potential species may lead to incorrect equilibrium calculations (that is does not necessary mean poor description of real case scenario). Additionally, the model does not account for kinetics or activation energy, which are crucial for understanding the speed of reactions and the energy barriers that must be overcome for reactions to occur. As a result, while the model can predict the equilibrium state, it cannot guarantee that the real CO2 with impurities system actually reach that state.\n\nThe model uses neqsim library for the fluid description (EOS).", valid_substances=['H2O', 'SO2', 'SO3', 'NO2', 'NO', 'H2S', 'O2', 'H2SO4', 'HNO3', 'S8', 'CH4', 'H2O', 'O2', 'H2SO4', 'NH4NO3', 'NH4HSO4', 'CH2O2', 'CH3COOH', 'CH3OH', 'CH4', 'CO', 'CH3CH2OH', 'CO', 'HOCH2CH2OH', '(CH2CH2OH)2O', 'HOCH2(CH2CH2O)2CH2OH', 'H2NCH2CH2OH', 'CH3N(C2H4OH)2', '(CH2CH2OH)2NH', 'CH3CH3', 'CH3CH2CH3', '(CH3)2CHCH3', 'CH3CH2CH2CH3', 'CH3(CH2)3CH3', 'C6H5CH3', 'C6H4(CH3)2', 'HCN', 'CS2', 'Ar', 'CH2O', 'C2H4O', 'C2H4', 'CH3CHO', 'H2', 'N2O3', 'N2', 'N2H4', 'COS', 'NH3'], parameters={'equationOfState': _Parameter(default='SRK', label='Equation of State', unit=None, type=None)}), Model(access_error=None, model_id='phpitz', display_name='pHPitz', description='Computational model developed by Baard Kaasa as part of our CCS research on CO2 Impurities.', valid_substances=['O2', 'H2O', 'H2S', 'SO2', 'NO2', 'N2', 'NO', 'H2SO4', 'HNO3', 'S8', 'NH3', 'N2O', 'N2O4', 'NH4HSO4', 'HCHO', 'CH3CHO', 'CH3COCH3', 'HCOOH', 'CH3COOH'], parameters={})])

In [3]:
concs = {
    "O2": 30,
    "H2O": 30,
    "H2S": 0,
    "SO2": 10,
    "NO2": 20,
}
params = {}
T = 200  # K
P = 10  # bar a

In [4]:
session.run_model("tocomo", concs, params, temperature=T, pressure=T)

         H2O  H2S        NO  H2SO4  HNO2   S8         O2  SO2  NO2       HNO3
0  10.000508  0.0  0.001016   10.0   0.0  0.0  20.000762  0.0  0.0  19.998984

In [5]:
dfs = []
for value in range(10, 50, 5):
    df = session.run_model(
        "phpitz", {**concs, "H2O": value}, params, temperature=T, pressure=T
    )
    df.set_index([pd.Series([value], name="H2O[in]")], inplace=True)
    dfs.append(df)
df = pd.concat(dfs)
df

,CH3CHO,HCHO,NO,S8,O2,N2O,HNO3,NO2,N2O4,H2O,CH3COCH3,NH3,H2S,N2,H2SO4,NH4HSO4,SO2,CH3COOH,HCOOH
H2O[in],,,,,,,,,,,,,,,,,,,
10,0.0,0.0,0.3704,0.0,30.0204,0.0001,0.0311,19.5982,0.0001,9.6705,0.0,0.0,0.0,0.0,0.3140,0.0,9.6860,0.0,0.0
15,0.0,0.0,0.3707,0.0,29.9440,0.0001,0.0381,19.5909,0.0001,14.5175,0.0,0.0,0.0,0.0,0.4635,0.0,9.5365,0.0,0.0
20,0.0,0.0,0.3711,0.0,29.8704,0.0001,0.0439,19.5847,0.0001,19.3698,0.0,0.0,0.0,0.0,0.6083,0.0,9.3918,0.0,0.0
25,0.0,0.0,0.3714,0.0,29.7991,0.0001,0.0491,19.5793,0.0001,24.2270,0.0,0.0,0.0,0.0,0.7485,0.0,9.2515,0.0,0.0
30,0.0,0.0,0.3717,0.0,29.7301,0.0001,0.0537,19.5743,0.0001,29.0887,0.0,0.0,0.0,0.0,0.8845,0.0,9.1155,0.0,0.0
35,0.0,0.0,0.3721,0.0,29.6633,0.0001,0.0580,19.5697,0.0001,33.9547,0.0,0.0,0.0,0.0,1.0164,0.0,8.9836,0.0,0.0
40,0.0,0.0,0.3724,0.0,29.5985,0.0001,0.0620,19.5654,0.0001,38.8247,0.0,0.0,0.0,0.0,1.1443,0.0,8.8557,0.0,0.0
45,0.0,0.0,0.3727,0.0,29.5356,0.0001,0.0657,19.5613,0.0001,43.6986,0.0,0.0,0.0,0.0,1.2686,0.0,8.7314,0.0,0.0